
name: CI with Gradle

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0

    - name: Docker build & push to docker repo
      run: |
          docker login -u kuploy -p Klusterjoa18!
          docker build -t kuploy/ls -f Dockerfile .
          docker push kuploy/ls

